### ISSUE TITLE
rpmalloc_thread_initialize required?

### ISSUE THREAD

**Issue by Muzza** [CoherentLabs/rpmalloc#4]
The Usage section of the readme implies that rpmalloc_thread_initialize does not need to be called in this modified version of rpmalloc, however I don't think this is true?

I've found that if rpmalloc is called from any thread other than the one that called rpmalloc_initialize, it will crash due to the thread heap being uninitialized. If this is expected behaviour, then I think the readme needs rewording. Currently I have to call rpmalloc_thread_initialize on every thread that will use rpmalloc to avoid a crash.

Also, minor point, but rpmalloc.cpp does not compile if asserts are enabled.

**Comment by stoyannk** [comment]
Fixed the README to be more clear; fixed the asserts-on build
