### ISSUE TITLE
Compilation issues under MSVC with ENABLE_VALIDATE_ARGS

### ISSUE THREAD

**Issue by BobbyAnguelov** [CoherentLabs/rpmalloc#5]
if you enable the ENABLE_VALIDATE_ARGS feature, you get a compilation error since you are using the #ifdef PLATFORM_WINDOWS macro instead of RPMALLOC_PLATFORM_WIN, fixing that macro highlights missing system headers needed for the validation code path.

**Comment by stoyannk** [comment]
Fixed
