### ISSUE TITLE
Wrong range check when allocating large spans

### ISSUE THREAD

**Issue by mjansson** [CoherentLabs/rpmalloc#7]
https://github.com/CoherentLabs/rpmalloc/blob/8a841182f474d4fada7fa8ceac7375c929495759/rpmalloc/rpmalloc.cpp#L780

Look at https://github.com/rampantpixels/rpmalloc/issues/46 and the fix in https://github.com/rampantpixels/rpmalloc/commit/f9b1bb4f100401b54de193bf8f75218db403763f

**Comment by stoyannk** [comment]
Thank you, fixed in 67e07a425b81e8cd79bf079f4e253f1c19372c8c
