### ISSUE TITLE
Tag large spans traversing global cache

### ISSUE THREAD

**Issue by mjansson** [CoherentLabs/rpmalloc#8]
There is a missing heap tag for spans that have potentially traversed the global span cache (fixed upstream). If the global cache returns multiple spans they will be put in the large span cache for the heap, but the heap id is not tagged for all (and thus needs to be done when extracting the span from the heap large cache).

https://github.com/CoherentLabs/rpmalloc/blob/8a841182f474d4fada7fa8ceac7375c929495759/rpmalloc/rpmalloc.cpp#L795-L798

Add a chunk to tag:

```
//Mark span as owned by this heap
span->heap_id = heap->id;
std::atomic_thread_fence(std::memory_order_release);
```

**Comment by stoyannk** [comment]
Thank you, fixed in 67e07a425b81e8cd79bf079f4e253f1c19372c8c
